title: Mohammad Qtaishat
email: mohammadqtaishat95@gmail.com
description: >-
  Portfolio and professional architecture documentation.
theme: minima
header_pages:
  - index.md
  - experience.md
  - technical_skills.md
